### ISSUE TITLE
Action hits deprecation warnings

### ISSUE THREAD

**Issue by MikeBishop** [cryptic-wizard/run-behave-tests#2]
Running the basic config specified on the Action page results in:

```
Run cryptic-wizard/run-behave-tests@v0.3.0
Run python -m pip install --upgrade pip -q
  
Requirements file requirements.txt not found
Run pip install behave -q
  
  DEPRECATION: parse is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
Behave artifact full path = tests/results.txt
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by cryptic-wizard** [comment]
Thanks for the issue report, Mike.

v0.4.0 is updated to use ```actions/upload-artifact@v4``` and ```actions/setup-python@v5```
Note: v0.3.0 will be deprecated November 30, 2024 with ```actions/upload-artifact@v3```
The [deprecation warning for v0.3.0](https://github.com/marketplace/actions/run-behave-tests#features) is also on the github action marketplace page

Additionally, there is a bug fix so the artifact name will actually match the ```test-output-name``` input
